graph LR
    A[Web Crawlers] --> B[Apache Tika] --> C[Post-Processing] --> D[Topic Model Enrollment]
    D --> E[Jensen-Shannon & <br/> Kullback-Leibler <br/> Divergence Scores] 
    E --> F[Unsupervised <br/> Clustering]
    E --> G[Novelty <br/> Scoring]
    F --> C 
    F --> D
    G --> C
    G --> D
    H[Monitoring & <br/> Feedback] --> C
    H[Monitoring & <br/> Feedback] --> D
    H[Monitoring & <br/> Feedback] --> F

    subgraph Ingest Pipeline
        A
        B
    end

    subgraph Topic Model
        D[Topic Model Enrollment <br/> PostgreSQL <br/> with pgvector]
        E[Jensen-Shannon & <br/> Kullback-Leibler <br/> Divergence Scores <br/> PostgreSQL <br/> with pgvector]
    end

    subgraph Eviction Cache
        C[Post-Processing <br/> Redis]
        F[Unsupervised <br/> Clustering]
        G[Novelty <br/> Scoring]
    end

    subgraph Data Storage
        I[Raw Crawled Data <br/> ZFS on 2.5TB] 
        J[Processed Documents <br/> Parquet on 2.5TB]
        K[Topic Model Outputs <br/> PostgreSQL <br/> with pgvector]
        L[Cluster Assignments <br/> PostgreSQL]
    end

    subgraph Monitoring & Feedback
        H
    end
